// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpM_Z33bcS7e0aTri-1ESMCRGvqjn3w_k',
    appId: '1:945396274774:web:ba454e96b9db1b701c8df7',
    messagingSenderId: '945396274774',
    projectId: 'e-tailor-app-885bd',
    authDomain: 'e-tailor-app-885bd.firebaseapp.com',
    storageBucket: 'e-tailor-app-885bd.firebasestorage.app',
    measurementId: 'G-JWNQK20XCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqebz0j-3eFdQM3BKO30BdG9vx5i5Ay4I',
    appId: '1:945396274774:android:3d2c821c66cea3b81c8df7',
    messagingSenderId: '945396274774',
    projectId: 'e-tailor-app-885bd',
    storageBucket: 'e-tailor-app-885bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpq8vqOZXIuZjBaL__KUm8yLxV2C2-fRY',
    appId: '1:945396274774:ios:d6073ac4dc66e6331c8df7',
    messagingSenderId: '945396274774',
    projectId: 'e-tailor-app-885bd',
    storageBucket: 'e-tailor-app-885bd.firebasestorage.app',
    iosBundleId: 'com.example.etailor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpq8vqOZXIuZjBaL__KUm8yLxV2C2-fRY',
    appId: '1:945396274774:ios:d6073ac4dc66e6331c8df7',
    messagingSenderId: '945396274774',
    projectId: 'e-tailor-app-885bd',
    storageBucket: 'e-tailor-app-885bd.firebasestorage.app',
    iosBundleId: 'com.example.etailor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpM_Z33bcS7e0aTri-1ESMCRGvqjn3w_k',
    appId: '1:945396274774:web:562207fad6fe93151c8df7',
    messagingSenderId: '945396274774',
    projectId: 'e-tailor-app-885bd',
    authDomain: 'e-tailor-app-885bd.firebaseapp.com',
    storageBucket: 'e-tailor-app-885bd.firebasestorage.app',
    measurementId: 'G-K5BPX3CYY7',
  );
}
